server.port=8080
spring.application.name=jira-testgen

# CORS
spring.web.cors.allowed-origins=http://localhost:3000

# Jira Configuration ? fill in your values
jira.base-url=https://gssathiyanarayan.atlassian.net
jira.email=gssathiyanarayan@gmail.com
jira.api-token=ATATT3xFfGF0wsiVJ4NuH8_iwWunwJ1UwQlx1llDiifTcj0nztm1Slm0hORAy8Lj1uOhDAWjv8RLxCNFGnCa2TWDSsQxCA3o3jQtGmK3sQWU4jfnSR8hz_FYkqcRItymxoDUyFiEppVEPoJgsRPQzaSy2qFDHMUFjqQTGi9F39cW9yXwMpmh994=625CA9A6

# Confluence Configuration ? fill in your values
confluence.base-url=https://gssathiyanarayan.atlassian.net
confluence.email=gssathiyanarayan@gmail.com
confluence.api-token=ATATT3xFfGF0wsiVJ4NuH8_iwWunwJ1UwQlx1llDiifTcj0nztm1Slm0hORAy8Lj1uOhDAWjv8RLxCNFGnCa2TWDSsQxCA3o3jQtGmK3sQWU4jfnSR8hz_FYkqcRItymxoDUyFiEppVEPoJgsRPQzaSy2qFDHMUFjqQTGi9F39cW9yXwMpmh994=625CA9A6
confluence.space-keys=DEV,QA,DOCS

# Gemini AI Configuration ? fill in your values
gemini.api-key=AQ.Ab8RN6Iu5y77133f5AX384oVJhzdErHBPk-0e8Xi-d8Cv1q2ow

logging.level.com.testgen=DEBUG
